### ISSUE TITLE
apply python module import logic

### ISSUE THREAD

**Issue by PnPie** [bndr/pycycle#2]
It seems that in this moment, the program only takes into account the importation statement in each file, not integrated the python modules loading logic with context, for example, for the `tests/_projects/large_circle` case, if I change the `tests/_projects/large_circle/a_module/a_file.py` just by moving the function before import statement like this:
```
def a_func():
    return "a func"

from a_module.b_module.b_file import b_func
```
Then this test case should be fine and we can run it successfully, but the program still give us circular import error.

**Comment by bndr** [comment]
Thanks for the bug report! I'll look into it
